### ISSUE TITLE
Sobre los paquetes

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada6/jrpg#3]
Distribuyan en distintos paquetes los conceptos relacionados con la _raza_, la _casta_, los _ítems_.
Eso les permitirá hacer crecer el proyecto ordenadamente.
Hoy en día, al estar todo al mismo nivel, se hace complicada la exploración:  
![selection_455](https://cloud.githubusercontent.com/assets/684051/19620690/c8dd3276-9858-11e6-8426-ec4b3a94085e.png)

**Comment by aretamar** [comment]
Se reorganizaron las clases en distintos paquetes.

**Comment by delucas** [comment]
:+1:
