### ISSUE TITLE
Sobre las carpetas espurias

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada6/jrpg#4]
Carpetas como `.recommenders` no deben estar en el proyecto.
Por favor, [eliminarlas del repositorio](http://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste) y agregarlas a `.gitignore` para que no vuelvan a aparecer.

**Comment by aretamar** [comment]
Se eliminó del repositorio la carpeta .recommenders y se agregó la excepción en .gitignore

**Comment by aretamar** [comment]
Se cierra el issue
