### ISSUE TITLE
Sobre las salidas por pantalla

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada6/jrpg#6]
No es bueno utilizar salidas por pantalla del tipo `System.out.println`.
El juego no se ejecuta en la consola, por lo que todos esos mensajes, no serán visualizado por nadie.

Eliminen las ocurrencias de este tipo de salidas.

**Comment by aretamar** [comment]
Se eliminaron los System.out.println del código

**Comment by delucas** [comment]
Excelente! Cerra el issue la próxima, por favor :)
