### ISSUE TITLE
Sobre los Tests comentados

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada6/jrpg#7]
No es una buena práctica comentar los tests que no funcionan (ejemplo, `ItemTests`).
En cambio, disponen de `@Ignore` para aclara qué pruebas no deben ser ejecutadas.

Eviten tener código comentado en el repositorio, porque luego se convierte en un :skull:

**Comment by aretamar** [comment]
Se agregó @Ignore sobre los tests  que no están finalizados y se eliminó el código comentado

**Comment by delucas** [comment]
Excelente! Cerra el issue la próxima, por favor :)
